### ISSUE TITLE
What is the IP connection during install?

### ISSUE THREAD

**Issue by gjf** [xanasoft/Sandboxie#7]
![Безымянный](https://user-images.githubusercontent.com/322186/79139152-721d4300-7dbe-11ea-837c-b92126e65ee8.png)
Any comments?

**Comment by DavidXanatos** [comment]
The setup script as provided by sophos has a to https://www.sandboxie.com/
see line 773 in .\Sandboxie\install\SandboxieVS.nsi

I'll remove that in the next builds.
